### ISSUE TITLE
libyui-gtk (2.46.0) fails to build with latest libyui 3.9.3

### ISSUE THREAD

**Issue by david-geiger** [libyui/libyui-gtk#67]
Hi,

I tried on Mageia 7 to build latest git snapshot (2.46.0) against new libyui 3.9.3 but it fails to build with:

> /home/david/mgarepo/02_KDE_STACK/re2/libmirage/libyui/libyui-gtk/BUILD/libyui-gtk-2.46.0/src/YGDumbTab.cc: In member function 'virtual YDumbTab* YGOptionalWidgetFactory::createDumbTab(YWidget*)':
/home/david/mgarepo/02_KDE_STACK/re2/libmirage/libyui/libyui-gtk/BUILD/libyui-gtk-2.46.0/src/YGDumbTab.cc:161:31: error: invalid new-expression of abstract class type 'YGDumbTab'
 { return new YGDumbTab (parent); }
                               ^
/home/david/mgarepo/02_KDE_STACK/re2/libmirage/libyui/libyui-gtk/BUILD/libyui-gtk-2.46.0/src/YGDumbTab.cc:15:7: note:   because the following virtual functions are pure within 'YGDumbTab':
 class YGDumbTab : public YDumbTab, public YGWidget
       ^~~~~~~~~
In file included from /home/david/mgarepo/02_KDE_STACK/re2/libmirage/libyui/libyui-gtk/BUILD/libyui-gtk-2.46.0/src/YGDumbTab.cc:10:
/usr/include/yui/YDumbTab.h:151:18: note: 	'virtual void YDumbTab::activate()'
     virtual void activate() = 0;
                  ^~~~~~~~
make[2]: *** [src/CMakeFiles/yui-gtk.dir/build.make:118: src/CMakeFiles/yui-gtk.dir/YGDumbTab.cc.o] Error 1
make[2]: Leaving directory '/home/david/mgarepo/02_KDE_STACK/re2/libmirage/libyui/libyui-gtk/BUILD/libyui-gtk-2.46.0/build'
make[2]: *** Waiting for unfinished jobs....

Regards,
David
[log.libyui-gtk.txt](https://github.com/libyui/libyui-gtk/files/4259838/log.libyui-gtk.txt)
